#name: Publish Python distributions to PyPI and TestPyPI on tagged commits using poetry
name: pypi

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-n-publish:
    name: Build and publish Python distributions to PyPI and TestPyPI
    runs-on: ubuntu-20.04

    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
    #- name: Build and publish distribution to Test PyPI
    #  uses: JRubics/poetry-publish@v1.5
    #  with:
    #    python_version: '3.9'
    #    pypi_token: ${{ secrets.TEST_PYPI_API_TOKEN }}
    #    repository_url: 'https://test.pypi.org/legacy/'
    - name: Build and publish distribution to PyPI
      uses: JRubics/poetry-publish@v1.16
      with:
        python_version: '3.9'
        pypi_token: ${{ secrets.PYPI_API_TOKEN }}
