#name: Publish Docker image to Docker Hub on tagged commits
name: docker

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  push-to-registry:
    name: Publish Docker image to Docker Hub
    runs-on: ubuntu-20.04

    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
      with:
        submodules: 'true'
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build image and push it to Docker Hub
      uses: docker/build-push-action@v2
      with:
        context: .
        pull: true
        push: true
        cache-from: type=registry,ref=snovvcrash/divideandscan:latest
        cache-to: type=inline
        tags: snovvcrash/divideandscan:latest
